/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import communication.Communication;
import controller.ControllerUI;
import domain.Administrator;
import form.employees.EmployeesForm;
import form.projects.ProjectsForm;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import session.Session;

public class MainForm extends javax.swing.JFrame {

   
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblUserText3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelEmployeeItem = new javax.swing.JPanel();
        lblUserText = new javax.swing.JLabel();
        lblUserPhoto = new javax.swing.JLabel();
        panelProjectsItem = new javax.swing.JPanel();
        lblProjectText = new javax.swing.JLabel();
        lblProjectPhoto = new javax.swing.JLabel();
        panelLogoutItem = new javax.swing.JPanel();
        lblLogoutText = new javax.swing.JLabel();
        lblLogoutPhoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 550));
        setResizable(false);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setMaximumSize(new java.awt.Dimension(900, 550));
        panelMain.setMinimumSize(new java.awt.Dimension(900, 550));
        panelMain.setPreferredSize(new java.awt.Dimension(900, 550));

        panelHeader.setBackground(new java.awt.Color(45, 118, 232));

        lblUser.setBackground(new java.awt.Color(45, 118, 232));
        lblUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblUserText3.setBackground(new java.awt.Color(45, 118, 232));
        lblUserText3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        lblUserText3.setForeground(new java.awt.Color(255, 255, 255));
        lblUserText3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserText3.setText("Welcome");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main.png"))); // NOI18N

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUserText3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(lblUserText3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUser)))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        panelEmployeeItem.setBackground(new java.awt.Color(240, 240, 240));
        panelEmployeeItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEmployeeItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEmployeeItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEmployeeItemMouseExited(evt);
            }
        });

        lblUserText.setBackground(new java.awt.Color(45, 118, 232));
        lblUserText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserText.setForeground(new java.awt.Color(45, 118, 232));
        lblUserText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserText.setText("Employees");

        lblUserPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        lblUserPhoto.setText("jLabel1");
        lblUserPhoto.setMaximumSize(new java.awt.Dimension(48, 48));
        lblUserPhoto.setMinimumSize(new java.awt.Dimension(48, 48));
        lblUserPhoto.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelEmployeeItemLayout = new javax.swing.GroupLayout(panelEmployeeItem);
        panelEmployeeItem.setLayout(panelEmployeeItemLayout);
        panelEmployeeItemLayout.setHorizontalGroup(
            panelEmployeeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeItemLayout.createSequentialGroup()
                .addGroup(panelEmployeeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmployeeItemLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelEmployeeItemLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblUserText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelEmployeeItemLayout.setVerticalGroup(
            panelEmployeeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeItemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblUserPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblUserText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelProjectsItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProjectsItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelProjectsItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelProjectsItemMouseExited(evt);
            }
        });

        lblProjectText.setBackground(new java.awt.Color(45, 118, 232));
        lblProjectText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProjectText.setForeground(new java.awt.Color(45, 118, 232));
        lblProjectText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProjectText.setText("Projects");

        lblProjectPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/projects.png"))); // NOI18N
        lblProjectPhoto.setText("jLabel1");
        lblProjectPhoto.setMaximumSize(new java.awt.Dimension(48, 48));
        lblProjectPhoto.setMinimumSize(new java.awt.Dimension(48, 48));
        lblProjectPhoto.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelProjectsItemLayout = new javax.swing.GroupLayout(panelProjectsItem);
        panelProjectsItem.setLayout(panelProjectsItemLayout);
        panelProjectsItemLayout.setHorizontalGroup(
            panelProjectsItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsItemLayout.createSequentialGroup()
                .addGroup(panelProjectsItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProjectsItemLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblProjectPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelProjectsItemLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblProjectText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelProjectsItemLayout.setVerticalGroup(
            panelProjectsItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProjectsItemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblProjectPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblProjectText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLogoutItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLogoutItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLogoutItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLogoutItemMouseExited(evt);
            }
        });

        lblLogoutText.setBackground(new java.awt.Color(45, 118, 232));
        lblLogoutText.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLogoutText.setForeground(new java.awt.Color(45, 118, 232));
        lblLogoutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogoutText.setText("Log Out");

        lblLogoutPhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        lblLogoutPhoto.setText("jLabel1");
        lblLogoutPhoto.setMaximumSize(new java.awt.Dimension(48, 48));
        lblLogoutPhoto.setMinimumSize(new java.awt.Dimension(48, 48));
        lblLogoutPhoto.setPreferredSize(new java.awt.Dimension(48, 48));

        javax.swing.GroupLayout panelLogoutItemLayout = new javax.swing.GroupLayout(panelLogoutItem);
        panelLogoutItem.setLayout(panelLogoutItemLayout);
        panelLogoutItemLayout.setHorizontalGroup(
            panelLogoutItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutItemLayout.createSequentialGroup()
                .addGroup(panelLogoutItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogoutItemLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblLogoutPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLogoutItemLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblLogoutText, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelLogoutItemLayout.setVerticalGroup(
            panelLogoutItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoutItemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblLogoutPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblLogoutText)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(panelEmployeeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(panelProjectsItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(panelLogoutItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEmployeeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProjectsItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLogoutItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 322, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, 640, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelEmployeeItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeeItemMouseEntered
        setColor(panelEmployeeItem);
    }//GEN-LAST:event_panelEmployeeItemMouseEntered

    private void panelEmployeeItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeeItemMouseExited
        resetColor(panelEmployeeItem);
    }//GEN-LAST:event_panelEmployeeItemMouseExited

    private void panelProjectsItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProjectsItemMouseEntered
        setColor(panelProjectsItem);
    }//GEN-LAST:event_panelProjectsItemMouseEntered

    private void panelProjectsItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProjectsItemMouseExited
        resetColor(panelProjectsItem);
    }//GEN-LAST:event_panelProjectsItemMouseExited

    private void panelLogoutItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutItemMouseEntered
        setColor(panelLogoutItem);
    }//GEN-LAST:event_panelLogoutItemMouseEntered

    private void panelLogoutItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutItemMouseExited
        resetColor(panelLogoutItem);
    }//GEN-LAST:event_panelLogoutItemMouseExited

    private void panelLogoutItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLogoutItemMouseClicked
        Administrator admin = (Administrator) Session.getInstance().get("loggedInUser");
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?");
        if (result == JOptionPane.YES_OPTION) {
            try {
                admin = ControllerUI.getInstance().logout(admin);
                Communication.getInstance().getSocket().close();
                JOptionPane.showMessageDialog(this, "Goodbye, " + admin.getUsername());
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Error while logging out from application");
            } 
            System.exit(0);
        }

    }//GEN-LAST:event_panelLogoutItemMouseClicked

    private void panelEmployeeItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeeItemMouseClicked
        new EmployeesForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelEmployeeItemMouseClicked

    private void panelProjectsItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProjectsItemMouseClicked
        new ProjectsForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_panelProjectsItemMouseClicked

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(240, 240, 240));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogoutPhoto;
    private javax.swing.JLabel lblLogoutText;
    private javax.swing.JLabel lblProjectPhoto;
    private javax.swing.JLabel lblProjectText;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUserPhoto;
    private javax.swing.JLabel lblUserText;
    private javax.swing.JLabel lblUserText3;
    private javax.swing.JPanel panelEmployeeItem;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelLogoutItem;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelProjectsItem;
    // End of variables declaration//GEN-END:variables



}
